# Generated by Django 3.1.5 on 2021-05-25 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('file_id', models.CharField(default='None', max_length=200, primary_key=True, serialize=False)),
                ('url', models.CharField(default='None', max_length=1000)),
                ('title', models.CharField(default='None', max_length=200)),
                ('name', models.CharField(default='None', max_length=200)),
                ('claSS', models.CharField(default='None', max_length=20)),
                ('order', models.CharField(default='None', max_length=20)),
                ('family', models.CharField(default='None', max_length=20)),
                ('describe', models.CharField(default='None', max_length=2000)),
                ('feature', models.CharField(default='None', max_length=2000)),
                ('size', models.CharField(default='None', max_length=2000)),
                ('habitat', models.CharField(default='None', max_length=2000)),
                ('inner', models.CharField(default='None', max_length=1000)),
                ('outer', models.CharField(default='None', max_length=1000)),
                ('level', models.CharField(default='None', max_length=20)),
                ('others', models.CharField(default='None', max_length=2000)),
                ('time', models.DateTimeField(default=datetime.datetime(2021, 5, 1, 0, 0))),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure_id', models.CharField(default='None', max_length=200)),
                ('url', models.CharField(default='None', max_length=1000)),
                ('real_type', models.CharField(default='None', max_length=50)),
                ('real_denomination', models.CharField(default='None', max_length=50)),
                ('real_code', models.CharField(default='None', max_length=50)),
                ('real_year', models.CharField(default='None', max_length=50)),
                ('view', models.CharField(max_length=50)),
                ('predict_type', models.CharField(default='None', max_length=50)),
                ('predict_denomination', models.CharField(default='None', max_length=50)),
                ('predict_code', models.CharField(default='None', max_length=50)),
                ('predict_year', models.CharField(default='None', max_length=50)),
                ('time', models.DateTimeField(default=datetime.datetime(2021, 5, 1, 0, 0))),
            ],
        ),
    ]
