# Generated by Django 3.1.5 on 2021-05-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='view',
            field=models.CharField(choices=[('正面', 'Front'), ('背面', 'Back')], default='正面', max_length=50),
        ),
    ]
