# Generated by Django 3.1.5 on 2021-05-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_auto_20210525_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='id',
        ),
        migrations.AlterField(
            model_name='currency',
            name='figure_id',
            field=models.CharField(default='None', max_length=200, primary_key=True, serialize=False),
        ),
    ]
